spring:
  application:
    name: jobport

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect   # (?? ???? ??)

  liquibase:
    change-log: classpath:/db/migration.yml
#    enabled: false

auth:
  kakao:
    client-id: ${KAKAO_REST_API_KEY}
    response-type: code
    authorize-uri: https://kauth.kakao.com/oauth/authorize
    redirect-uri: ${KAKAO_REDIRECT_URI}
    client-secret: ${KAKAO_CLIENT_SECRET}

server:
  servlet:
    session:
      timeout: 30m